### ISSUE TITLE
邀请收录进： awesome-github-profile-readme-chinese

### ISSUE THREAD

**Issue by eryajf** [zkeq/zkeq#1]
你好，你的个人主页很赞，我做了一个中文区优秀个人主页合集的项目，特邀请你参与贡献。

项目地址：https://github.com/eryajf/awesome-github-profile-readme-chinese

**Comment by zkeq** [comment]
wow，这个项目感觉很不错诶，感谢邀请，有个疑问就是关于截图.

我的主页里面展开的歌词也要截图么？会不会太长了

**Comment by zkeq** [comment]
已提pr：https://github.com/eryajf/awesome-github-profile-readme-chinese/pull/6
